services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - micro-net
    restart: unless-stopped
  
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./mongo_data:/mongo_data
    ports:
      - 27017:27017
    restart: unless-stopped
    
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    restart: unless-stopped

  mail-dev:
    image: maildev/maildev
    container_name: mail_dev
    ports:
      - 1080:1080
      - 1025:1025
    restart: unless-stopped

networks:
  micro-net:
    driver: bridge
