spring.cloud.config.override-system-properties=false

eureka.instance.hostname=eureka-server
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:8761/eureka/

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
